# Generated by Django 5.0.7 on 2026-03-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trial_ends_at', models.DateTimeField()),
                ('subscription_status', models.CharField(default='TRIAL', max_length=20)),
                ('primary_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('secondary_color', models.CharField(default='#7EC8FF', max_length=20)),
            ],
        ),
    ]
