# Generated by Django 5.0.7 on 2026-03-03 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=30)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professionals', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('duration_min', models.PositiveIntegerField(default=30)),
                ('price_cents', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('CONFIRMED', 'Confirmado'), ('COMPLETED', 'Concluído'), ('NO_SHOW', 'Ausente'), ('CANCELED', 'Cancelado')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.tenant')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheduling.customer')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheduling.professional')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheduling.service')),
            ],
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'phone'], name='scheduling__tenant__965dee_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['tenant', 'starts_at'], name='scheduling__tenant__012f99_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['professional', 'starts_at'], name='scheduling__profess_150d0c_idx'),
        ),
    ]
